### ISSUE TITLE
Alex's task list for software tutorial

### ISSUE THREAD

**Issue by alexandertuna** [alexandertuna/muoncollider#1]
- [x] Big picture
  - [x] Create website
  - [x] Walk through all steps with a student
  - [x] Make PR to muon-collider-wiki (first)
- [x] Feedback
  - [x] Ask Rose/Elise for analysis code
  - [x] Ask Paolo about 2.9 functionality
  - [x] Make PR to MuC-Tutorial (first)
  - [x] Update PR to MuC-Tutorial (second)
- [x] Content
  - [x] Add particle gun
  - [x] Add sim
  - [x] Add digi
  - [x] Add reco
  - [x] Add how to add Marlin processor
  - [x] Add short analysis of track, cluster, PFO vs truth (pyroot)
  - [x] Add short analysis of track, cluster, PFO vs truth (Pandas)
  - [x] Add BIB overlay (intermediate)
  - [x] Add BIB overlay (advanced)
  - [x] Run bib advanced instructions (digi)
  - [x] Run bib advanced instructions (reco)
  - [x] Add BIB event display script
  - [x] <del>Add VSCode tips for apptainer/ap23</del>
  - [x] Rerun analysis scripts in 2.9.1
  - [x] <del>Add LCTuple info</del>
  - [x] Update triple backticks to legitimacy
  - [x] Update multi-line comments to legitimacy
  - [x] Add batch info
  - [x] <del>Add html drawing of gen/sim/digi/reco workflow</del>
  - [x] <del>Add html drawing of bib workflow</del>
  - [x] <del>Add calibration a la Rose/Elise?</del>
